"use client";
import { useState } from "react";
import { Plus, Trash2, Copy, Download } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect } from "@/components/ui/native-select";
import { emptyWorkflow, workflowSchema, taskKinds, taskCalendar, preparationDraft, type BidTask, type BidWorkflow } from "@/lib/procurement-workbench";
import { todayJst, type BidInput, type Bid } from "@/lib/bid-domain";

export default function BidWorkflowEditor({draft,onChange}:{draft:BidInput;onChange:(value:string)=>void}){
  // Keep intermediate input (an empty title or partially typed URL) until save validates it.
  const workflow:BidWorkflow=(()=>{try{const value=JSON.parse(draft.workflow||"{}");return {...emptyWorkflow(),...value,tasks:Array.isArray(value.tasks)?value.tasks:[],result:{...emptyWorkflow().result,...value.result}};}catch{return emptyWorkflow();}})();
  const [text,setText]=useState(""),[message,setMessage]=useState("");
  const update=(patch:Partial<BidWorkflow>)=>onChange(JSON.stringify({...workflow,...patch}));
  const task=(id:string,patch:Partial<BidTask>)=>update({tasks:workflow.tasks.map(t=>t.id===id?{...t,...patch}:t)});
  const result=(patch:Partial<BidWorkflow["result"]>)=>update({result:{...workflow.result,...patch}});
  const bid={...draft,id:(draft as Bid).id||workflow.candidateId||"draft",source:"manual",createdBy:"",createdAt:0,updatedAt:0,revision:1} as Bid;
  const download=()=>{if(!workflowSchema.safeParse(workflow).success){setMessage("作業名・日付・結果の入力内容を確認してから書き出してください。");return;}const url=URL.createObjectURL(new Blob([taskCalendar(bid)],{type:"text/calendar;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="SFL-bid-deadlines.ics";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("日付を登録した未完了の作業を書き出しました。更新時はカレンダー側も更新してください。");};
  return <>
    <fieldset className="editor-section"><legend><span>04</span>作業・必要書類・先行手続き</legend><p>説明会や参加申請も、提出期限とは別に管理します。時刻は日本時間です。</p>
      <div className="task-editor-list">{workflow.tasks.map(t=><article className="task-editor" key={t.id}><div className="task-editor-title"><label><input type="checkbox" checked={t.done} onChange={e=>task(t.id,{done:e.target.checked})}/><span className="sr-only">{t.title}を完了にする</span></label><Input aria-label="作業名" value={t.title} maxLength={200} onChange={e=>task(t.id,{title:e.target.value})}/><button type="button" className="icon-button" aria-label={`${t.title}を削除`} onClick={()=>update({tasks:workflow.tasks.filter(v=>v.id!==t.id)})}><Trash2 size={17}/></button></div><div className="workbench-grid"><label>作業の種類<NativeSelect value={t.kind} onChange={e=>task(t.id,{kind:e.target.value as BidTask["kind"]})}>{Object.entries(taskKinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</NativeSelect></label><label>担当者<Input value={t.owner} maxLength={150} onChange={e=>task(t.id,{owner:e.target.value})} placeholder="氏名を入力"/></label><label>期限日<Input type="date" value={t.date} onChange={e=>task(t.id,{date:e.target.value})}/></label><label>期限時刻<Input type="time" value={t.time} onChange={e=>task(t.id,{time:e.target.value})}/></label><label className="full">原文の記載・必要書類<Input value={t.evidence} maxLength={1000} onChange={e=>task(t.id,{evidence:e.target.value})} placeholder="資料名・ページ・該当する記載"/></label></div>{!t.done&&t.date&&t.date<todayJst()&&<p className="text-danger">期限日を過ぎています。対応状況を確認してください。</p>}</article>)}</div>
      <div className="actions"><button type="button" className="button secondary" disabled={workflow.tasks.length>=40} onClick={()=>update({tasks:[...workflow.tasks,{id:crypto.randomUUID(),title:"新しい作業",kind:"other",date:"",time:"",owner:"",evidence:"",done:false}]})}><Plus size={17}/>作業を追加</button><button type="button" className="button secondary" disabled={!workflow.tasks.some(t=>t.date&&!t.done)} onClick={download}><Download size={17}/>期限をカレンダーへ</button></div><p className="form-hint">変更は最後に「案件を保存」で確定します。カレンダーへの書き出しは自動同期ではありません。</p>
    </fieldset>
    <fieldset className="editor-section"><legend><span>05</span>結果と振り返り</legend><p>公開結果または確認できた事実を入力。不明な金額は空欄にします。</p><div className="workbench-grid"><label>落札企業<Input value={workflow.result.winner} maxLength={200} onChange={e=>result({winner:e.target.value})}/></label><label>結果公表日<Input type="date" value={workflow.result.date} onChange={e=>result({date:e.target.value})}/></label><label>落札金額（円）<Input inputMode="decimal" value={workflow.result.amount} maxLength={30} onChange={e=>result({amount:e.target.value})} placeholder="不明・非公表の場合は空欄"/></label><label>金額の税区分<NativeSelect value={workflow.result.tax} onChange={e=>result({tax:e.target.value as BidWorkflow["result"]["tax"]})}><option value="unknown">未確認</option><option value="included">税込</option><option value="excluded">税抜</option></NativeSelect></label><label className="full">結果の出典URL<Input type="url" value={workflow.result.sourceUrl} maxLength={2000} onChange={e=>result({sourceUrl:e.target.value})}/></label><label className="full">結果・見送りの理由と次への改善<Textarea value={workflow.result.reason} maxLength={2000} onChange={e=>result({reason:e.target.value})}/></label></div></fieldset>
    <fieldset className="editor-section"><legend><span>06</span>質問・提案の準備</legend><p>登録した情報を使い、原文確認と追記のための構成メモを作ります。</p><div className="actions"><button type="button" className="button secondary" onClick={()=>setText(preparationDraft(bid,"question"))}>質問文のひな形</button><button type="button" className="button secondary" onClick={()=>setText(preparationDraft(bid,"proposal"))}>提案書の構成メモ</button></div>{text&&<><Textarea aria-label="書類準備の構成メモ" rows={12} value={text} onChange={e=>setText(e.target.value)}/><button type="button" className="button secondary" onClick={()=>void navigator.clipboard.writeText(text).then(()=>setMessage("コピーしました。編集した構成メモは、保存先の書類へ貼り付けてください。")).catch(()=>setMessage("コピーできませんでした。文章を選択してコピーしてください。"))}><Copy size={16}/>文章をコピー</button><p className="form-hint">この欄の編集は案件保存の対象外です。作成した文章はコピーして保管してください。</p></>}</fieldset>
    {message&&<p className="workbench-success" role="status">{message}</p>}
  </>;
}
