"use client";
import { useEffect, useState } from "react";
import { CalendarClock, ArrowUpRight, RefreshCw, CircleAlert } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table";
import { workbenchRequest } from "./procurement-tools";
import { statusLabels, todayJst, type Bid } from "@/lib/bid-domain";
import { taskKinds, type BidTask, type BidWorkflow } from "@/lib/procurement-workbench";
type Insights={tasks:(BidTask&{bidId:string;bidTitle:string;officialUrl:string})[];results:(Bid&{result:BidWorkflow["result"]})[];competitors:{winner:string;count:number;knownAmounts:number;includedTotal:number;excludedTotal:number;unknownTaxTotal:number}[];stats:{managed:number;unassigned:number;overdue:number;won:number;lost:number;winRate:number|null};truncated:boolean};
export default function BidInsights({onOpen,compact=false,revision=0}:{onOpen:(id:string)=>void;compact?:boolean;revision?:number}){
  const [data,setData]=useState<Insights|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[query,setQuery]=useState(""),[period,setPeriod]=useState("all");
  useEffect(()=>{let active=true;workbenchRequest<Insights>("/api/bid-insights").then(v=>{if(active){setData(v);setError("");}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[refresh,revision]);
  const today=todayJst(),taskList=(data?.tasks??[]).filter(t=>(t.title+t.bidTitle+t.owner).toLowerCase().includes(query.toLowerCase())&&(period==="all" ? true : period==="undated" ? !t.date : period==="overdue" ? !!t.date&&t.date<today : t.date===today));
  const results=(data?.results??[]).filter(b=>(b.title+b.agency+b.result.winner+b.result.reason).toLowerCase().includes(query.toLowerCase()));
  const taskRows=(limit:number)=><div className="deadline-cards">{taskList.slice(0,limit).map(t=><article key={t.bidId+t.id} className={`deadline-card ${t.date&&t.date<today?"overdue":""}`}><div><span className="task-kind">{taskKinds[t.kind]}</span><strong>{t.date||"期限未設定"} {t.time}</strong></div><div><h3>{t.title}</h3><button className="text-button" onClick={()=>onOpen(t.bidId)}>{t.bidTitle}</button><p>担当：{t.owner||"未割当"}</p>{t.evidence&&<small>{t.evidence}</small>}</div><button className="button secondary" onClick={()=>onOpen(t.bidId)}>確認・更新<ArrowUpRight size={16}/></button></article>)}{!taskList.length&&<div className="discovery-empty"><CalendarClock size={28}/><h3>該当する未完了の作業はありません</h3><p>案件の詳細で作業と期限を登録すると、ここに表示されます。</p></div>}</div>;
  if(compact)return <section className="panel"><div className="panel-heading"><h2>次にすること・先行手続き</h2><a href="#insights" className="text-button">すべての作業を見る<ArrowUpRight size={16}/></a></div>{error?<p className="app-error" role="alert">{error}</p>:data?taskRows(5):<p>作業を読み込んでいます…</p>}</section>;
  return <div className="bid-insights"><div className="insight-metrics">{[["管理中の案件",data?.stats.managed],["未割当の対応案件",data?.stats.unassigned],["期限超過の作業",data?.stats.overdue],["受注率",data?.stats.winRate===null?"未集計":data?`${data.stats.winRate}%`:undefined]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value??"—"}</strong></div>)}</div><p className="form-hint">このポータルに登録した案件の集計です。受注率は「受注・完了 ÷（受注・完了＋不採択）」で計算します。</p>
  {error&&<p className="app-error" role="alert">{error}</p>}{data?.truncated&&<p className="app-error">更新の新しい5,000件を集計しています。</p>}
  <section className="panel"><div className="insight-toolbar"><Input aria-label="案件・担当者・落札企業を検索" placeholder="案件名・担当者・落札企業で絞り込み" value={query} onChange={e=>setQuery(e.target.value)}/><button className="button secondary" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={17}/>更新</button></div><Tabs defaultValue="tasks"><TabsList><TabsTrigger value="tasks">作業・期限</TabsTrigger><TabsTrigger value="results">落札・対応結果</TabsTrigger><TabsTrigger value="competitors">落札企業の集計</TabsTrigger></TabsList><TabsContent value="tasks"><label className="deadline-select">期限で絞り込み<NativeSelect value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">すべて</option><option value="today">本日</option><option value="overdue">期限超過</option><option value="undated">期限未設定</option></NativeSelect></label>{data?taskRows(100):<p>読み込んでいます…</p>}{taskList.length>100&&<p>先頭100件を表示しています。案件名・担当者で絞り込んでください。</p>}</TabsContent>
  <TabsContent value="results"><p className="form-hint">案件の詳細に記録した結果です。全国の落札結果の自動収集は未接続です。</p><Table><TableHeader><TableRow><TableHead>案件・発注機関</TableHead><TableHead>対応結果</TableHead><TableHead>落札企業</TableHead><TableHead>公表金額</TableHead><TableHead>出典</TableHead></TableRow></TableHeader><TableBody>{results.slice(0,100).map(b=><TableRow key={b.id}><TableCell><button className="text-button" onClick={()=>onOpen(b.id)}>{b.title}</button><p>{b.agency}</p></TableCell><TableCell>{statusLabels[b.status]}</TableCell><TableCell>{b.result.winner||"未確認"}</TableCell><TableCell>{b.result.amount?`${Number(b.result.amount).toLocaleString()}円（${{unknown:"税区分未確認",included:"税込",excluded:"税抜"}[b.result.tax]}）`:"未確認・非公表"}</TableCell><TableCell>{b.result.sourceUrl?<a href={b.result.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-button">結果の原文<ArrowUpRight size={16}/></a>:"未登録"}</TableCell></TableRow>)}</TableBody></Table>{data&&!results.length&&<div className="discovery-empty"><h3>該当する結果はありません</h3><p>案件を受注・不採択・見送りなどに更新し、確認できた結果を記録してください。</p></div>}</TabsContent>
  <TabsContent value="competitors"><p className="form-hint">登録された落札企業別の集計です。税込・税抜・未確認の金額は分けています。企業名の表記違いは自動統合していません。</p><Table><TableHeader><TableRow><TableHead>落札企業</TableHead><TableHead>記録件数</TableHead><TableHead>金額確認件数</TableHead><TableHead>税込の合計</TableHead><TableHead>税抜の合計</TableHead><TableHead>税区分未確認の合計</TableHead></TableRow></TableHeader><TableBody>{data?.competitors.filter(c=>c.winner.toLowerCase().includes(query.toLowerCase())).map(c=><TableRow key={c.winner}><TableCell>{c.winner}</TableCell><TableCell>{c.count}</TableCell><TableCell>{c.knownAmounts}</TableCell><TableCell>{c.includedTotal.toLocaleString()}円</TableCell><TableCell>{c.excludedTotal.toLocaleString()}円</TableCell><TableCell>{c.unknownTaxTotal.toLocaleString()}円</TableCell></TableRow>)}</TableBody></Table>{data&&!data.competitors.length&&<div className="discovery-empty"><CircleAlert size={25}/><h3>落札企業の記録はまだありません</h3><p>結果を蓄積すると、企業別の受注状況を比較できます。</p></div>}</TabsContent></Tabs></section></div>;
}
